# Generated by Django 3.2.4 on 2021-06-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/', verbose_name='Product image'),
        ),
    ]
