# Generated by Django 3.2.4 on 2021-06-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_listing_category_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Category'),
        ),
    ]
