# Generated by Django 3.2.4 on 2021-06-08 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='id',
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='watcher', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
